name: mirrorchyan

on:
  workflow_dispatch:

jobs:
  mirrorchyan:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        os: [win, osx, linux]
        arch: [arm64, x64]

    steps:
      - uses: MirrorChyan/uploading-action@v1
        if: always()
        with:
          filetype: latest-release
          fileName: "MFAAvalonia-*-${{ matrix.os }}-${{ matrix.arch }}.zip"
          mirrorchyan_rid: YuanMFA

          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}
